name: soundpool
description: A Flutter Sound Pool for playing short audio files. Sound tracks are cached in memory and played directly from cache.
version: 2.3.0
homepage: https://github.com/ukasz123/soundpool/tree/master/soundpool

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: '>=3.3.5'

dependencies:
  flutter:
    sdk: flutter

  soundpool_platform_interface:
    path: ../soundpool_platform_interface
  
  soundpool_web:
    path: ../soundpool_web

flutter:
  plugin:
    platforms:
      android:
        package: pl.ukaszapps.soundpool
        pluginClass: SoundpoolPlugin
      ios:
        pluginClass: SoundpoolPlugin
      web:
        default_package: soundpool_web
